# Configuration file describing the aesthetics of a scatter plot
# displaying the results of a dimensionality reduction analysis.
#
# The file also contains the options specifying the output file format
# where the plot will be saved.


#######################################################################


# Set the options for the output file 
# (passed to 'matplotlib.pyplot.savefig').
#
# All the available options to set up the output file can be found at:
#
# https://matplotlib.org/stable/api/_as_gen/
# matplotlib.pyplot.savefig.html
output:
  
  # Set the DPI (the higher the number, the higher the resolution).
  #
  # Type: int.
  dpi: 300
  
  # Set whether to have a transparent background.
  #
  # Type: bool.
  transparent: True
  
  # Set the format of the output file.
  #
  # Type: str.
  #
  # Options: all the available options can be found at
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.pyplot.savefig.html
  format: png
  
  # Set the bounding box in inches.
  #
  # Type: str or list of floats.
  #
  # Options: all the available options can be found at
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.pyplot.savefig.html
  bbox_inches: tight


#######################################################################


# Set the font properties that will apply to all text elements of
# all plots.
#
# If different specifications are provided for some text elements,
# those specifications will take precedence.
font_properties:

  # Set the name of/path to the font.
  #
  # Type: str.
  fname: /Users/lcb518/Documents/fonts/Poppins/Poppins-Light.ttf


#######################################################################


# Set the options for the plot. These options will be used for all the
# sub-plots, unless different options are specified in the sections
# named after the single plots.
plot:

  # Set the options for the scatterplot (passed to
  # 'seaborn.scatterplot').
  #
  # All the available options to set up the scatterplot can be found
  # at:
  #
  # https://seaborn.pydata.org/generated/seaborn.scatterplot.html
  scatterplot:

    # Set the palette to be used to color the markers.
    #
    # Type: str.
    #
    # Options: all the available options can be found at:
    # https://seaborn.pydata.org/generated/seaborn.scatterplot.html
    palette: husl

  # Set the options for the data points not belonging to groups of
  # interest, if any groups of interest were specified.
  other_groups:

    # Set the color of the points.
    #
    # Type: str.
    #
    # Options: all the available options can be found at:
    # https://seaborn.pydata.org/generated/seaborn.scatterplot.html
    color: "#cccccc"

    # Set the alpha for the points.
    #
    # Type: float.
    #
    # Options: all the available options can be found at:
    #
    # https://seaborn.pydata.org/generated/seaborn.scatterplot.html
    alpha: 0.8


  #####################################################################


  # Set the options for the legend (passed to
  # 'matplotlib.axes.Axes.legend').
  #
  # All the available options to set up the legend can be found at:
  #
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.axes.Axes.legend.html
  legend:

    # Set whether the legend should be surrounded by a frame.
    #
    # Type: bool.
    frameon: False

    # Set the legend's title.
    #
    # Type: str.
    title: Groups

    # Set the alignment of the legend's elements.
    #
    # Type: str.
    #
    # Options: all the available options can be found at
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.legend.html
    alignment: left

    # Set the absolute position of the legend (1.0, 1.0 roughly means
    # "center right").
    #
    # Type: list of float.
    bbox_to_anchor: [1.3, 0.9]

    # Set the number of columns of the legend - adjust this according
    # to the number of legend elements you have.
    #
    # Type: int.
    ncols: 2
    
    # Set the properties of the font of the legend's text elements.
    #
    # All the the available options for the properties can be found at:
    #
    # https://matplotlib.org/stable/api/
    # font_manager_api.html#matplotlib.font_manager.FontProperties
    prop:
      
      # Set the font size.
      #
      # Type: int.
      size: 8

    # Set the properties of the font of the legend's title.
    # 
    # All the available options for the properties can be found at:
    #
    # https://matplotlib.org/stable/api/
    # font_manager_api.html#matplotlib.font_manager.FontProperties
    title_fontproperties:
      
      # Set the font size.
      #
      # Type: int.
      size: 10


  #####################################################################


  # Set the options for the x-axis.
  xaxis:
    
    # Set the options for the axis' label (passed to
    # 'matplotlib.axes.Axes.set_xlabel').
    #
    # All the available options to set up the axis' label can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_xlabel.html
    label:

      # Set the axis' label.
      #
      # Type: str.
      xlabel: C1

      # Set the properties of the font of the axis' label.
      #
      # All the available options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the font size.
        #
        # Type: int.
        size: 10

    #-----------------------------------------------------------------#
    
    # Set the ticks' labels.
    ticklabels:

      # Set the options for the ticks' labels (passed to 
      # 'matplotlib.axes.Axes.set_xticklabels').
      #
      # All the available options to set up the ticks' labels can be
      # found at:
      #
      # https://matplotlib.org/stable/api/_as_gen/
      # matplotlib.axes.Axes.set_xticklabels.html
      options:
      
        # Set the rotation of the ticks' labels.
        #
        # Type: float.
        rotation: 0.0

        # Set the properties of the font of the ticks' labels.
        #
        # All the available options for the properties can be found at:
        #
        # https://matplotlib.org/stable/api/
        # font_manager_api.html#matplotlib.font_manager.FontProperties
        fontproperties:
          
          # Set the font size.
          #
          # Type: int.
          size: 8

    #-----------------------------------------------------------------#

    # Set the options for the interval represented on the axis.
    interval:

      # Set the type of interval represented on the axis.
      #
      # Type: str.
      #
      # Options:
      # - 'discrete' for a discrete interval.
      # - 'continuous' for a continuous interval.
      type: continuous


  #####################################################################


  # Set the options for the y-axis.
  yaxis:
    
    # Set the options for the axis' label (passed to
    # 'matplotlib.axes.Axes.set_ylabel').
    #
    # All the available options to set up the axis' label can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_ylabel.html
    label:

      # Set the axis' label.
      #
      # Type: str.
      ylabel: C2

      # Set the properties of the font of the axis' label.
      #
      # All the available options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the font size.
        #
        # Type: int.
        size: 10

    #-----------------------------------------------------------------#
    
    # Set the ticks' labels.
    ticklabels:

      # Set the options for the ticks' labels (passed to 
      # 'matplotlib.axes.Axes.set_yticklabels').
      #
      # All the available options to set up the ticks' labels can be
      # found at:
      #
      # https://matplotlib.org/stable/api/_as_gen/
      # matplotlib.axes.Axes.set_yticklabels.html
      options:
      
        # Set the rotation of the ticks' labels.
        #
        # Type: float.
        rotation: 0.0

        # Set the properties of the font of the ticks' labels.
        #
        # All the available options for the properties can be found at:
        #
        # https://matplotlib.org/stable/api/
        # font_manager_api.html#matplotlib.font_manager.FontProperties
        fontproperties:
          
          # Set the font size.
          #
          # Type: int.
          size: 8

    #-----------------------------------------------------------------#

    # Set the options for the interval represented on the axis.
    interval:

      # Set the type of interval represented on the axis.
      #
      # Type: str.
      #
      # Options:
      # - 'discrete' for a discrete interval.
      # - 'continuous' for a continuous interval.
      type: continuous
