# Configuration file describing the aesthetics of a histogram. The
# bins may be colored according to their height, and a vertical line
# may be drawn on the plot. The file also contains the options
# specifying the format of the output file where the plot will be
# saved.
#
# All available options can be found at:
#
# https://bulkdgd.readthedocs.io/en/latest/histograms.html


#######################################################################


# Set the options for the output file.
#
# All the available options to set up the output file can be found at:
#
# https://bulkdgd.readthedocs.io/en/latest/outputs.html
output:
  
  # Set the DPI (dots per inch) of the output file.
  #
  # Type: int.
  dpi: 900
  
  # Set whether the figure's background is transparent. It is 'False'
  # by default.
  #
  # Type: bool.
  transparent: True
  
  # Set the figure's bounding box in inches.
  #
  # Type: str.
  #
  # Options: 'standard' or 'tight'.
  bbox_inches: tight


#######################################################################


# Set the general font properties.
#
# All the available options for the properties can be found at:
#
# https://bulkdgd.readthedocs.io/en/latest/text_elements.html
general_fontproperties:

  # Set the name of/path to the font.
  #
  # Type: str.
  #
  # Notes: if !!null, the default font used by Matplotlib will be
  # used.
  fname: !!null


#######################################################################


# Set the options for the figure.
figure:

  # Set the options to adjust the sub-plots.
  #
  # All the available options to adjust the sub-plots can be found
  # at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/figures.html
  subplots:

    # Set the horizontal space between the sub-plots as a fraction of
    # the average width of the x-axis.
    #
    # Type: int or float.
    wspace: 0.7

    # Set the vertical space between the sub-plots as a fraction of
    # the average height of the y-axis.
    #
    # Type: int or float.
    hspace: 0.7


#######################################################################


# Set the options for the histogram.
#
# All the available options to set up the histogram can be found at:
#
# https://bulkdgd.readthedocs.io/en/latest/histograms.html
histogram:

  # Set the number of bins in the histogram.
  #
  # Type: int.
  num_bins: 100

  # Set whether to plot a density or a count. It is 'False' by
  # default.
  # 
  # Remember to set the label of the y-axis accordingly so that
  # it represents the quantity displayed on the axis.
  #
  # Type: bool.
  density: True

  # Set the alpha blending value, between 0 (transparent) and 1
  # (opaque).
  #
  # Type: int or float.
  alpha: 1.0


#######################################################################


# Set the options for the color bar.
#
# This section can be safely removed from the configuration if you
# do not want to color the bins according to their height.
#
# All the available options to set up the colorbar can be found at:
#
# https://bulkdgd.readthedocs.io/en/latest/histograms.html
colorbar:

  # Set the colormap to be used. It must be the name of a Matplotlib
  # colormap.
  #
  # Type: str.
  #
  # Options: all the available options can be found at
  # https://matplotlib.org/stable/users/explain/colors/colormaps.html
  cmap: summer_r

  #-------------------------------------------------------------------#

  # Set the options for the color bar.
  #
  # All the available options to set up the color bar can be found
  # at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/histograms.html
  options:

    # Extend the color bar for out-of-range values. 'neither' means
    # no extensions, 'both' means both ends are extended, and 'min'
    # and 'max' mean that only the lower or upper end of the color
    # bar is extended. If '!!null', no extension is applied.
    #
    # Type: str.
    extend: both

  #-------------------------------------------------------------------#

  # Set the options for the color bar's axis' label.
  #
  # All the available options to set up the color bar's axis' label
  # can be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/histograms.html
  label:

    # Set the padding around the label.
    #
    # Type: int.
    labelpad: 10

    # Set the font properties of the label.
    fontproperties:

      # Set the font size.
      #
      # Type: int.
      size: 16

  #-------------------------------------------------------------------#

  # Set the axis' ticks' labels.
  #
  # All the available options to set up the color bar's axis' ticks'
  # labels can be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/histograms.html
  ticklabels:

    # Set the format for the ticks' labels.
    #
    # Type: format str.
    fmt: "{:.3f}"

    # Set the options for the ticks' labels.
    options:
    
      # Set the font properties of the ticks' labels.
      fontproperties:

        # Set the font size.
        #
        # Type: int.
        size: 12

  #-------------------------------------------------------------------#

  # Set the options for the interval represented on the color bar's
  # axis.
  #
  # All the available options to set up the interval can be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/histograms.html
  interval:

    # Set type of interval displayed on the axis.
    #
    # Type: str.
    #
    # Options:
    # - 'discrete' for a discrete interval.
    # - 'continuous' for a continuous interval.  
    type: continuous

    # Set whether to round all ticks' positions to the nearest
    # 'round_to_nearest' number. For instance, setting it to 1 would
    # round to the nearest integer, while setting it to 0.5 would
    # round to the nearest half an integer.
    #
    # If the interval is 'discrete', it is set to 1 by default.
    # If the interval is 'continuous', it is set to 0.5 by default.
    #
    # Type: int or float.
    # round_to_nearest: !!null

    # Set the highest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed.
    #
    # Type: int or float.
    top: 1.0

    # Set the lowest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed).
    #
    # Type: int or float.
    # bottom: !!null

    # Set the number of steps (ticks) displayed on the axis. This
    # number includes the most extreme ticks. It is set to 10 by
    # default.
    #
    # Type: int.
    # steps: !!null

    # Set the spacing between the ticks on the axis. If not passed,
    # it is automatically computed from the 'top', 'bottom', and
    # 'steps' values.
    #
    # Type: int or float.
    spacing: 0.1


#######################################################################


# Set the options for the plot's title.
#
# All the available options to set up the plot's title can be found
# at:
#
# https://bulkdgd.readthedocs.io/en/latest/titles.html
title:

  # Set the padding around the title.
  #
  # Type: int.
  pad: 20

  # Set the font properties of the title.
  fontproperties:
    
    # Set the font size.
    #
    # Type: int.
    size: 18


#######################################################################


# Set the options for the x-axis.
xaxis:
  
  # Set the options for the axis' label.
  #
  # All the available options to set up the axis' label can be found
  # at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/xaxis.html
  label:

    # Set the padding around the label.
    #
    # Type: int.
    labelpad: 10

    # Set the font properties of the label.
    fontproperties:

      # Set the font size.
      #
      # Type: int.
      size: 16

  #-------------------------------------------------------------------#
  
  # Set the axis' ticks' labels.
  #
  # All the available options to set up the axis' ticks' labels can
  # be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/xaxis.html
  ticklabels:
    
    # Set the format for the ticks' labels.
    #
    # Type: format str.
    fmt: "{:d}"

    # Set the options for the ticks' labels.
    options:

      # Set the font properties of the ticks' labels.
      fontproperties:

        # Set the font size.
        #
        # Type: int.
        size: 12

  #-------------------------------------------------------------------#

  # Set the options for the interval represented on the axis.
  #
  # All the available options to set up the interval can be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/xaxis.html
  interval:

    # Set the type of interval represented on the axis.
    #
    # Type: str.
    #
    # Options:
    # - 'discrete' for a discrete interval.
    # - 'continuous' for a continuous interval.
    type: continuous

    # Set whether to round all ticks' positions to the nearest
    # 'round_to_nearest' number. For instance, setting it to 1 would
    # round to the nearest integer, while setting it to 0.5 would
    # round to the nearest half an integer.
    #
    # If the interval is 'discrete', it is set to 1 by default.
    # If the interval is 'continuous', it is set to 0.5 by default.
    #
    # Type: int or float.
    # round_to_nearest: !!null

    # Set the highest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed.
    #
    # Type: int or float.
    top: 10

    # Set the lowest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed).
    #
    # Type: int or float.
    bottom: -10

    # Set the number of steps (ticks) displayed on the axis. This
    # number includes the most extreme ticks. It is set to 10 by
    # default.
    #
    # Type: int.
    # steps: !!null

    # Set the spacing between the ticks on the axis. If not passed,
    # it is automatically computed from the 'top', 'bottom', and
    # 'steps' values.
    #
    # Type: int or float.
    spacing: 2


#######################################################################


# Set the options for the y-axis.
yaxis:
  
  # Set the options for the axis' label.
  #
  # All the available options to set up the axis' label can be found
  # at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/yaxis.html
  label:

    # Set the label.
    #
    # Type: str.
    ylabel: Density

    # Set the padding around the label.
    #
    # Type: int.
    labelpad: 10

    # Set the font properties of the label.
    fontproperties:

      # Set the font size.
      #
      # Type: int.
      size: 16

  #-------------------------------------------------------------------#

  # Set the axis' ticks' labels.
  #
  # All the available options to set up the axis' ticks' labels can
  # be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/yaxis.html
  ticklabels:
  
    # Set the format for the ticks' labels.
    #
    # Type: format str.
    fmt: "{:.3f}"

    # Set the options for the ticks' labels.
    options:

      # Set the font properties of the ticks' labels.
      fontproperties:

        # Set the font size.
        #
        # Type: int.
        size: 12

  #-------------------------------------------------------------------#

  # Set the options for the interval represented on the axis.
  #
  # All the available options to set up the interval can be found at:
  #
  # https://bulkdgd.readthedocs.io/en/latest/yaxis.html
  interval:

    # Set the type of interval represented on the axis.
    #
    # Type: str.
    #
    # Options:
    # - 'discrete' for a discrete interval.
    # - 'continuous' for a continuous interval.
    type: continuous

    # Set whether to round all ticks' positions to the nearest
    # 'round_to_nearest' number. For instance, setting it to 1 would
    # round to the nearest integer, while setting it to 0.5 would
    # round to the nearest half an integer.
    #
    # If the interval is 'discrete', it is set to 1 by default.
    # If the interval is 'continuous', it is set to 0.5 by default.
    #
    # Type: int or float.
    # round_to_nearest: !!null

    # Set the highest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed.
    #
    # Type: int or float.
    top: 1.0

    # Set the lowest value displayed on the axis. It is
    # automatically inferred from the plot if not passed (and
    # appropriately rounded if the 'round_to_nearest' option is
    # passed).
    #
    # Type: int or float.
    bottom: 0.0

    # Set the number of steps (ticks) displayed on the axis. This
    # number includes the most extreme ticks. It is set to 10 by
    # default.
    #
    # Type: int.
    # steps: !!null

    # Set the spacing between the ticks on the axis. If not passed,
    # it is automatically computed from the 'top', 'bottom', and
    # 'steps' values.
    #
    # Type: int or float.
    spacing: 0.1


#######################################################################


# The options for drawing a vertical line on the plot.
#
# All the available options for setting up the vertical line can be
# found at:
#
# https://bulkdgd.readthedocs.io/en/latest/histograms.html
vline:

    # Set the x-coordinate of the vertical line.
    #
    # Type: int or float.
    x: 0.0

    # Set the style of the line.
    #
    # Type: str or tuple.
    #
    # Options:
    # - '-' or 'solid' for a solid line.
    # - '--' or 'dashed' for a dashed line.
    # - '-.' or 'dashdot' for a dash-dot line.
    # - ':' or 'dotted' for a dotted line.
    # - a tuple containing as the first element the offset to draw a
    #   dashed line ('float') and as the second element a tuple with
    #   a sequence of floats of even length describing the length of
    #   dashes and spaces in ink points ('float', 'float'). For
    #   instance, '(4, 1, 2, 1)' represents a sequence of 4-point
    #    and 2-point dashes separated by 1-point spaces.
    linestyle: --

    # Set how to draw the end caps if the lines are dashed.
    #
    # Type: str.
    #
    # Options:
    # - 'butt' for a flat cap.
    # - 'round' for a rounded cap.
    # - 'projecting' for a projecting cap.
    dash_capstyle: round

    # Set how to join line segments if the lines are dashed.
    #
    # Type: str.
    #
    # Options:
    # - 'miter' for a sharp corner.
    # - 'round' for a rounded corner.
    # - 'bevel' for a flat beveled corner.
    dash_joinstyle: round

    # Set the color of the line.
    #
    # Type: str or float.
    #
    # Options: all the available options can be found at
    # https://bulkdgd.readthedocs.io/en/latest/colors.html
    color: "#333333"
