seeds:
  seed: 61
  python_random: 61
  numpy: 61
  torch: 61
  torch_cuda: 61
  deterministic_algorithms: false
dtype: float64
bulkdgd_version: 2.0.1
torch_version: 2.7.1+rocm6.2.4
latent_random_state: null
device: cuda:0
