# Configuration file specifying the options to train the model.


#######################################################################


# Set the number of epochs to train the model for.
#
# Type: int.
epochs: 200

#-------------------------------------------------------------------#

# Set the options for the data loader. They are passed to the
# 'torch.utils.data.DataLoader' constructor.
data_loader:

  # Set how many samples per batch to load.
  #
  # Type: int.
  batch_size: 256

  # Set whether to reshuffle the data during every training epoch.
  #
  # Type: bool.
  shuffle: True

#-------------------------------------------------------------------#

# Set the options to train the Gaussian mixture model.
gmm:

  # Set the optimizer.
  optimizer:

    # Set the optimizer to be used.
    #
    # Type: str.
    #
    # Options:
    # - 'adam' for the Adam optimizer.
    name: adam

    # Set the options for the optimizer (they vary according to the
    # optimizer defined by 'optimizer_name').
    #
    # For the 'adam' optimizer, they will be passed to the
    # 'torch.optim.Adam' constructor.
    options:

      # Set these options if 'optimizer_name' is 'adam'.

      # Set the learning rate.
      #
      # Type: float.
      lr: 0.01

      # Set the weight decay.
      #
      # Type: float.
      weight_decay: 0.0

#-------------------------------------------------------------------#

# Set the options to train the decoder.
dec:

  # Set the optimizer.
  optimizer:

    # Set the optimizer to be used.
    #
    # Type: str.
    #
    # Options:
    # - 'adam' for the Adam optimizer.
    name: adam

    # Set the options for the optimizer (they vary according to the
    # optimizer defined by 'optimizer_name').
    #
    # For the 'adam' optimizer, they will be passed to the
    # 'torch.optim.Adam' constructor.
    options:

      # Set these options if 'optimizer_name' is 'adam'.

      # Set the learning rate.
      #
      # Type: float.
      lr: 0.0001

      # Set the weight decay.
      #
      # Type: float.
      weight_decay: 0.0

      # Set the betas.
      #
      # Type: list of float.
      betas: [0.5, 0.9]

#-------------------------------------------------------------------#

# Set the options to train the representation layer (the
# representations found for the samples).
rep:

  # Set the optimizer.
  optimizer:

    # Set the optimizer to be used.
    #
    # Type: str.
    #
    # Options:
    # - 'adam' for the Adam optimizer.
    name: adam

    # Set the options for the optimizer (they vary according to the
    # optimizer defined by 'optimizer_name').
    #
    # For the 'adam' optimizer, they will be passed to the
    # 'torch.optim.Adam' constructor.
    options:

      # Set these options if 'optimizer_name' is 'adam'.

      # Set the learning rate.
      #
      # Type: float.
      lr: 0.01

      # Set the weight decay.
      #
      # Type: float.
      weight_decay: 0.0

      # Set the betas.
      #
      # Type: list of float.
      betas: [0.5, 0.9]
