seeds:
  seed: 59
  python_random: 59
  numpy: 59
  torch: 59
  torch_cuda: 59
  deterministic_algorithms: false
dtype: float64
bulkdgd_version: 2.0.1
torch_version: 2.7.1+rocm6.2.4
latent_random_state: null
device: cuda:0
