# Configuration file specifying the options to get the representations
# with two rounds of optimization.


#######################################################################


# Set how many representations to initialize per sample per component
# of the Gaussian mixture model.
#
# Type: int.
n_rep_per_comp: 1


#######################################################################


# Set the options for the data loader.
data_loader:

  # Set how many samples per batch to load.
  batch_size: 8


#######################################################################


# Set the optimization scheme.
scheme: two_opt


#######################################################################

# Set the options for the first optimization round.
opt1:

  # Set the number of epochs.
  #
  # Type: int.
  epochs: 10

  # Set the optimizer.
  optimizer:

    # Set the name of the optimizer.
    #
    # Type: str.
    #
    # Options:
    # - 'adam' for the Adam optimizer.
    name: adam

    # Set the options for the optimizer (they vary according to the
    # optimizer defined by 'optimizer_name').
    options:

      # Set these options if 'optimizer_name' is 'adam'.

      # Set the learning rate.
      #
      # Type: float.
      lr: 0.01

      # Set the weight decay.
      #
      # Type: float.
      weight_decay: 0.0

      # Set the betas.
      #
      # Type: list of float.
      betas: [0.5, 0.9]

#---------------------------------------------------------------------#

# Set the options for the second optimization round.
opt2:

  # Set the number of epochs.
  #
  # Type: int.
  epochs: 50

  # Set the optimizer.
  optimizer:

    # Set the name of the optimizer.
    #
    # Type: str.
    #
    # Options:
    # - 'adam' for the Adam optimizer.
    name: adam

    # Set the options for the optimizer (they vary according to the
    # optimizer defined by 'optimizer_name').
    options:

      # Set these options if 'optimizer_name' is 'adam'.

      # Set the learning rate.
      #
      # Type: float.
      lr: 0.01

      # Set the weight decay.
      #
      # Type: float.
      weight_decay: 0.0

      # Set the betas.
      #
      # Type: list of float.
      betas: [0.5, 0.9]
