seeds:
  seed: 37
  python_random: 37
  numpy: 37
  torch: 37
  torch_cuda: 37
  deterministic_algorithms: false
dtype: float64
bulkdgd_version: 2.0.1
torch_version: 2.7.1+rocm6.2.4
latent_random_state: null
device: cuda:0
