

#------------------------------- Output ------------------------------#


# Output file settings (passed to 'matplotlib.pyplot.savefig')
output:
  
  # DPI (the higher the number, the higher the resolution)
  dpi: 900
  
  # Whether to have a transparent or opaque background
  transparent: True
  
  # Format of the output file
  format: pdf
  
  # Bbox in inches. If 'tight', use a tight layout for the figure
  bbox_inches: tight


#----------------------------- Histogram -----------------------------#


# Plot settings
plot:

  # Scatterplot settings
  scatterplot:

    # Palette to be used to color the markers
    palette: husl


  # Legend settings
  legend:

    # Whether the legend should be surrounded by a frame
    frameon: False

    # The legend's title
    title: Tissues

    # The alignment of the legend's elements
    alignment: left

    # The absolute position of the legend (1.0, 1.0 roughly means
    # "center right"
    bbox_to_anchor: [1.0, 1.0]

    # Number of columns of the legend - adjust this according to
    # the number of legend elements you have 
    ncols: 2
    
    # For properties of the legend's elements
    prop:

      # Name of/path to the font
      fname: !!null
      
      # Font size
      size: 8

    # For properties of the legend's title
    title_fontproperties:

      # Name of/path to the font
      fname: !!null
      
      # Font size
      size: 10


  # X-axis settings  
  xaxis:
    
    # Label settings (passed to
    # 'matplotlib.axes.Axes.set_xlabel')
    label:

      # Text for the label
      xlabel: PC1

      # Font properties of the label
      fontproperties:
        
        # Name of/path to the font
        fname: !!null
        
        # Font size
        size: 10
    
    # Tick labels settings (passed to 
    # 'matplotlib.axes.Axes.set_xticklabels')
    ticklabels:
      
      # Tick label rotation
      rotation: 0

      # Font properties of the tick labels
      fontproperties:
        
        # Name of/path to the font
        fname: !!null
        
        # Font size
        size: 8

    # Settings for the interval represented on the axis
    interval:

      # Type of interval ('discrete' or 'continuous')
      type: continuous


  # Y-axis settings
  yaxis:
    
    # Label settings (passed to
    # 'matplotlib.axes.Axes.set_ylabel')
    label:

      # Text for the label
      ylabel: PC2

      # Font properties of the label
      fontproperties:
        
        # Name of/path to the font
        fname: !!null
        
        # Font size
        size: 10
    
    # Tick labels settings (passed to
    # 'matplotlib.axes.Axes.set_yticklabels')
    ticklabels:
      
      # Tick label rotation
      rotation: 0

      # Font properties of the tick labels
      fontproperties:
        
        # Name of/path to the font
        fname: !!null
        
        # Font size
        size: 8

    # Settings for the interval represented on the axis
    interval:

      # Type of interval ('discrete' or 'continuous')      
      type: continuous
