genes_txt_file: "default"
latent_dim: 32
latent_type: tgmm
latent_options:
  n_components: 48
  covariance_type: tied_spherical
  init_covariances: empirical
  init_means: maxdist
  init_weights: uniform
  n_init: 1
  reg_covar: 1.0e-06
  tol: 0.0001
  random_state: null
  cem: false
decoder_options:
  activations:
  - relu
  - relu
  dropout: 0.0
  n_units_hidden_layers:
  - 500
  - 8000
  output_module_name: nb_full_dispersion
  output_module_options:
    activation: softplus

scaling_factor: "median"

dtype: "float64"
