seeds:
  seed: 71
  python_random: 71
  numpy: 71
  torch: 71
  torch_cuda: 71
  deterministic_algorithms: false
dtype: float64
bulkdgd_version: 2.0.1
torch_version: 2.7.1+rocm6.2.4
latent_random_state: null
device: cuda:0
