# Configuration file describing the aesthetics of a line plot
# displaying the CPU/wall clock time spent in each epoch of each
# round of optimization performed when finding the best representations
# for a set of sample.
#
# The file also contains the options specifying the output file format
# where the plot will be saved.


#######################################################################


# Set the options for the output file 
# (passed to 'matplotlib.pyplot.savefig').
#
# All the available options to set up the output file can be found at:
#
# https://matplotlib.org/stable/api/_as_gen/
# matplotlib.pyplot.savefig.html
output:
  
  # Set the DPI (the higher the number, the higher the resolution).
  #
  # Type: int.
  #
  # Default: 900.
  dpi: 900
  
  # Set whether to have a transparent background.
  #
  # Type: bool.
  #
  # Default: True.
  transparent: True
  
  # Set the format of the output file.
  #
  # Type: str.
  #
  # Options: all the available options can be found at
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.pyplot.savefig.html
  #
  # Default: 'pdf'.
  format: pdf
  
  # Set the bounding box in inches.
  #
  # Type: str or list of floats.
  #
  # Options: all the available options can be found at
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.pyplot.savefig.html
  #
  # Default: 'tight'.
  bbox_inches: tight


#######################################################################


# Set the options for the plot.
plot:

  # Set the options for the line plot (passed to 'seaborn.lineplot').
  #
  # All the available options to set up the line plot can be found at:
  #
  # https://seaborn.pydata.org/generated/seaborn.lineplot.html
  lineplot:

    # Set the palette to be used to color the lines.
    #
    # Type: str.
    #
    # Options: all the available options can be found at
    # https://seaborn.pydata.org/generated/seaborn.lineplot.html
    #
    # Default: 'husl'.
    palette: husl

  #-------------------------------------------------------------------#

  # Set the options for the legend (passed to
  # 'matplotlib.axes.Axes.legend').
  #
  # All the available options to set up the legend can be found at:
  #
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.axes.Axes.legend.html
  legend:

    # Set whether the legend should be surrounded by a frame.
    #
    # Type: bool.
    #
    # Default: False.
    frameon: False

    # Set the legend's title.
    #
    # Type: str.
    #
    # Default: 'Time (CPU/wall clock)'.
    title: Time (CPU/wall clock)

    # Set the alignment of the legend's elements.
    #
    # Type: str.
    #
    # Options: all the available options can be found at
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.legend.html
    #
    # Default: 'left'.
    alignment: left

    # Set the absolute position of the legend (1.0, 1.0 roughly means
    # "center right").
    #
    # Type: list of float.
    #
    # Default: [1.2, 0.9].
    bbox_to_anchor: [1.2, 0.9]

    # Set the number of columns of the legend - adjust this according
    # to the number of legend elements you have.
    #
    # Type: int.
    #
    # Default: 1.
    ncols: 1
    
    # Set the properties of the font of the legend's text elements.
    #
    # All the the availabe options for the properties can be found at:
    #
    # https://matplotlib.org/stable/api/
    # font_manager_api.html#matplotlib.font_manager.FontProperties
    prop:

      # Set the name of/path to the font.
      #
      # Type: str.
      #
      # Default: !!null (the default Matplotlib font will be used).
      fname: !!null
      
      # Set the font size.
      #
      # Type: int.
      #
      # Default: 8.
      size: 8

    # Set the properties of the font of the legend's title.
    # 
    # All the availabe options for the properties can be found at:
    #
    # https://matplotlib.org/stable/api/
    # font_manager_api.html#matplotlib.font_manager.FontProperties
    title_fontproperties:

      # Set the name of/path to the font.
      #
      # Type: str.
      #
      # Default: !!null (the default Matplotlib font will be used).
      fname: !!null
      
      # Set the font size.
      #
      # Type: int.
      #
      # Default: 10.
      size: 10

  #-------------------------------------------------------------------#

  # Set the options for the plot's title (passed to
  # 'matplotlib.axes.Axes.set_title').
  #
  # All the available options to set up the plot's title can be found
  # at:
  #
  # https://matplotlib.org/stable/api/_as_gen/
  # matplotlib.pyplot.title.html
  title:

    # Set the plot's title.
    #
    # Type: str.
    #
    # Default: 'Optimization round number [opt_round]'.
    #
    # Notes: [opt_round] will be replaced by the optimization
    # number in the plot.
    label: Optimization round number [opt_round]

    # Set the properties of the font of the plot's title.
    # 
    # All the availabe options for the properties can be found at:
    #
    # https://matplotlib.org/stable/api/
    # font_manager_api.html#matplotlib.font_manager.FontProperties
    fontproperties:
      
      # Set the name of/path to the font.
      #
      # Type: str.
      #
      # Default: !!null (the default Matplotlib font will be used).
      fname: !!null
      
      # Set the font size.
      #
      # Type: int.
      #
      # Default: 10.
      size: 10

  #-------------------------------------------------------------------#

  # Set the options for the x-axis.
  xaxis:
    
    # Set the options for the axis' label (passed to
    # 'matplotlib.axes.Axes.set_xlabel').
    #
    # All the available options to set up the axis' label can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_xlabel.html
    label:

      # Set the axis' label.
      #
      # Type: str.
      #
      # Default: 'Epoch'.
      xlabel: Epoch

      # Set the properties of the font of the axis' label.
      #
      # All the availabe options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the name of/path to the font.
        #
        # Type: str.
        #
        # Default: !!null (the default Matplotlib font will be used).
        fname: !!null
        
        # Set the font size.
        #
        # Type: int.
        #
        # Default: 10.
        size: 10
    
    # Set the options for the ticks' labels (passed to 
    # 'matplotlib.axes.Axes.set_xticklabels').
    #
    # All the available options to set up the ticks' labels can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_xticklabels.html
    ticklabels:
      
      # Set the rotation of the ticks' labels.
      #
      # Type: float.
      #
      # Default: 0.0.
      rotation: 0.0

      # Set the properties of the font of the ticks' labels.
      #
      # All the availabe options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the name of/path to the font.
        #
        # Type: str.
        #
        # Default: !!null (the default Matplotlib font will be used).
        fname: !!null
        
        # Set the font size.
        #
        # Type: int.
        #
        # Default: 10.
        size: 8

    # Set the options for the interval represented on the axis.
    interval:

      # Set the type of interval represented on the axis.
      #
      # Type: str.
      #
      # Options:
      # - 'discrete' for a discrete interval.
      # - 'continuous' for a continuous interval.
      #
      # Default: 'discrete'.
      type: discrete

      # Set the lowest value in the interval that will be represented
      # on the axis.
      #
      # Type: int or float.
      #
      # Default: 0.
      bottom: 0

      # Set the spacing of the values on the axis.
      #
      # Type: int or float.
      #
      # Default: 5.
      spacing: 5

  #-------------------------------------------------------------------#

  # Set the options for the y-axis.
  yaxis:
    
    # Set the options for the axis' label (passed to
    # 'matplotlib.axes.Axes.set_ylabel').
    #
    # All the available options to set up the axis' label can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_ylabel.html
    label:

      # Set the axis' label.
      #
      # Type: str.
      #
      # Default: 'Time (s)'.
      ylabel: Time (s)

      # Set the properties of the font of the axis' label.
      #
      # All the availabe options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the name of/path to the font.
        #
        # Type: str.
        #
        # Default: !!null (the default Matplotlib font will be used).
        fname: !!null
        
        # Set the font size.
        #
        # Type: int.
        #
        # Default: 10.
        size: 10
    
    # Set the options for the ticks' labels (passed to 
    # 'matplotlib.axes.Axes.set_yticklabels').
    #
    # All the available options to set up the ticks' labels can be
    # found at:
    #
    # https://matplotlib.org/stable/api/_as_gen/
    # matplotlib.axes.Axes.set_yticklabels.html
    ticklabels:
      
      # Set the rotation of the ticks' labels.
      #
      # Type: float.
      #
      # Default: 0.0.
      rotation: 0.0

      # Set the properties of the font of the ticks' labels.
      #
      # All the availabe options for the properties can be found at:
      #
      # https://matplotlib.org/stable/api/
      # font_manager_api.html#matplotlib.font_manager.FontProperties
      fontproperties:
        
        # Set the name of/path to the font.
        #
        # Type: str.
        #
        # Default: !!null (the default Matplotlib font will be used).
        fname: !!null
        
        # Set the font size.
        #
        # Type: int.
        #
        # Default: 10.
        size: 8

    # Set the options for the interval represented on the axis.
    interval:

      # Set the type of interval represented on the axis.
      #
      # Type: str.
      #
      # Options:
      # - 'discrete' for a discrete interval.
      # - 'continuous' for a continuous interval.
      #
      # Default: 'discrete'.    
      type: discrete
